### ISSUE TITLE
OpenJDK download via script not latest version - downloads 111 although 142 available

### ISSUE THREAD

**Issue by jr0cket** [AdoptOpenJDK/jdk9-jigsaw#11]
Using the getJigsawJDK.sh script a rather old version of Java SE Runtime appears to be quite old.
```
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+111-2016-03-30-163859.javare.4768.nc)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+111-2016-03-30-163859.javare.4768.nc, mixed mode)
```
This version of the Java SE does seem to work with the compile.sh scripts without modifying the -modulepath variable.

Should we be using a newer Java SE version, as can be downloaded from the Oracle website?

Thanks

**Comment by jr0cket** [comment]
Related to this issue I have created the following pull requests

#12 - Update version of JDK to download in the `getJigsawJDK.sh` script file
#13 - Update scripts to correct use of command line option syntax

Thank you

**Comment by neomatrix369** [comment]
Closing issue since PR is merged, reopen if not the case
