### ISSUE TITLE
It seems .tar.gz for Mac OS X is no more - getJigsaw.sh script

### ISSUE THREAD

**Issue by lasombra** [AdoptOpenJDK/jdk9-jigsaw#63]
Looking at the new download page for JDK 9, http://jdk.java.net/9/, it seems .tar.gz archives for Mac OS X are not available any more.

Using the new URL, http://download.java.net/java/jdk9/archive/169/binaries/jdk-9-ea+169_osx-x64_bin.dmg, and just renaming the extension to .tar.gz doesn't seem to work but it does work well for Linux.

**Comment by neomatrix369** [comment]
@lasombra is that an issue that this repo needs to handle? Is it a documentation change you are requesting or change to the way Oracle has published this information? If it's the later let's close this issue and take it up with Oracle separately.

**Comment by lasombra** [comment]
I am incredibly sorry about the poor reporting @neomatrix369. I wanted to mean that the download script `getJigsawJDK.sh` won't work, at least for now, for Mac OS X due to a change in packaging by Oracle.

**Comment by neomatrix369** [comment]
In that case please create a PR, the fix should be fairly easy to do - i'll merge it if you have tested it well before submitting it to me

**Comment by neomatrix369** [comment]
@lasombra issue is fixed via PR #64 - do you have any comments or feedback on this?

**Comment by lasombra** [comment]
Thanks for looking into it @neomatrix369 but, unfortunately, Oracle doesn't provide a .tar.gz for OS X anymore, just a .dmg.
