### ISSUE TITLE
Create separate get JDK binary scripts

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/jdk9-jigsaw#66]
Currently, we have `getJigsawJDK.sh` which download the JDK 9 EA binary from Oracle's site but it would be better to have one that download the JDK 9 EA binary and one that downloads the Jigsaw EA binary as they are served on two different download sites.

There is a difference in the binaries, that the Jigsaw binary always has the latest Jigsaw changes, while the Jigsaw changes in the JDK 9 EA binary may not always be up-to-date with Jigsaw changes.

Related to issue #63.

**Comment by lasombra** [comment]
The only problem I see here is that Mac builds are not offered as .tar.gz anymore. How should the .dmg be handled? Just download and let the user deal with it?

**Comment by neomatrix369** [comment]
Yes for dmg builds thats the best option, you can echo a message asking them to handle it from there onwards.

**Comment by neomatrix369** [comment]
Resolved by #67 and #68

**Comment by neomatrix369** [comment]
To be continued via new issues to resolve (https://github.com/AdoptOpenJDK/jdk9-jigsaw/pull/68#issuecomment-308574524)
