### ISSUE TITLE
Refactoring get JDK bash scripts

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/jdk9-jigsaw#69]
On the back of the comment https://github.com/AdoptOpenJDK/jdk9-jigsaw/pull/68#issuecomment-308574524 - some refactoring to simply script and improve readabality

**Comment by neomatrix369** [comment]
Would you be okay to address this enhancement lasombra? Let me know so I can assign it to you - thanks, its simple moving blocks of code to a common script

**Comment by lasombra** [comment]
@neomatrix369 Sure thing. I'll try to get it done during the week.

**Comment by neomatrix369** [comment]
Thanks @lasombra, looking forward to seeing the solution soon, good luck.

**Comment by neomatrix369** [comment]
Fixed by #70 - will revisit to see any further refactorings are needed - keeping in mind simplicity and readability
